import { readFile } from 'fs/promises';
import { resolve } from 'path';
import test from 'ava';

// csv-loader uses papaparse
import Papa from 'papaparse';
import { removeTLD } from '../source/libs/utils';
import { mediaRelationsToWebsitesMapping } from '../source/libs/parser';

test('Websites mapping', async t => {
  const csvFile = await readFile(resolve('./data/relations_medias_francais.tsv'), 'utf8');

  const parsed = Papa.parse(csvFile, {
    header: true,
    dynamicTyping: true,
    skipEmptyLines: true
  });

  const websitesToOwners = mediaRelationsToWebsitesMapping(parsed.data);

  const websitesList = [
    "lemonde.fr",
    "tf1.fr",
    "lci.fr",
    "lefigaro.fr",
    "lalettredelexpansion.com",
    "nouvelobs.com",
    "monde-diplomatique",
    "telerama.fr",
    "courrierinternational.com",
    "lavie.fr",
    "huffingtonpost.fr",
    "lesinrocks.com",
    "nova.fr",
    //"vice.com",
    "valeursactuelles.com",
    "slate.fr",
    "cnews.fr",
    "mycanal.fr",
    "canal.fr",
    "marianne.net",
    "lepoint.fr",
    "agefi.fr",
    "republicain-lorrain",
    "lejsl.com",
    "leprogres.fr",
    "ledauphine.com",
    "bienpublic.com",
    "lalsace.fr",
    "vosgesmatin.fr",
    "dna.fr",
    "estrepublicain.fr",
    "jhm.fr",
    "lepopulaire.fr",
    "lyonne.fr",
    "lechorepublicain.fr",
    "leberry.fr",
    "lejdc.fr",
    "lamontagne.fr",
    "larep.fr",
    "lanouvellerepublique.fr",
    "centre-presse",
    "tvtours.fr",
    "larepubliquedespyrenees.fr",
    "charentelibre.fr",
    "dordognelibre.fr",
    "sudouest.fr",
    "franceguyane.fr",
    "franceantilles.fr",
    "corsematin.com",
    "laprovence.com",
    "nicematin.com",
    "paris-normandie",
    "tebeo.bzh",
    "tebesud.bzh",
    "lepoher.fr",
    "letelegramme.fr",
    "nordeclair.fr",
    "courrier-picard",
    "lest-eclair",
    "nordlittoral.fr",
    "lardennais.fr",
    "lunion.fr",
    "aisnenouvelle.fr",
    "lavoixdunord.fr",
    "20minutes.fr",
    "ladepeche.fr",
    "petitbleu.fr",
    "nrpyrenees.fr",
    "lindependant.fr",
    "centrepresseaveyron.fr",
    "midilibre.fr",
    "ouest-france",
    "lemainelibre.fr",
    "lapressedelamanche.fr",
    "publihebdos.com",
    "presseocean.fr",
    "courrierdelouest.fr",
    "latribune.fr",
    "notretemps.com",
    "pelerin.com",
    "la-croix",
    "parismatch.com",
    "virginradio.fr",
    "gulli.fr",
    "rfm.fr",
    "europe1.fr",
    "lejdd.fr",
    "nrj.fr",
    "nrj-play",
    "cheriefm.fr",
    "nostalgie.fr",
    "rireetchansons.fr",
    "funradio.fr",
    "rtl.fr",
    "rtl2.fr",
    "m6.fr",
    "6play.fr",
    "capital.fr",
    "hbr.org",
    "vsd.fr",
    "bfmtv.com",
    "rmcbfmplay.com",
    "lexpress.fr",
    "liberation.fr",
    "lesechos.fr",
    "radioclassique.fr",
    "leparisien.fr",
    "aujourdhui-en-france",
    "lopinion.fr",
    "historia.fr",
    "lhistoire.fr",
    "larecherche.fr",
    "nouveau-magazine",
    "sciencesetavenir.fr",
    "challenges.fr",
    "fip.fr",
    "franceculture.fr",
    "franceinter.fr",
    "francemusique.fr",
    "francebleu.fr",
    "mouv.fr",
    "francetvinfo.fr",
    "france.tv",
    "tv5monde.com",
    "france24.com",
    "rfi.fr",
    "mc-doualiya",
    "lcp.fr",
    //"yahoo.com", // Unknown from CSV (Apollo fund)
    "arte.tv",
   // "theconversation.com", // Unknown from CSV (The conversation trust)
  ];

  for (const site of websitesList) {
    const hostWithoutTld = removeTLD(site);
    t.assert(websitesToOwners.has(hostWithoutTld), `Website ${site} cannot be mapped to a media group`);
  }
});